mysql:
  user: user
  port: 3306
  password: pass
  host: localhost
  database: database
PersonalWorlds: {}
spleef:
  world: Spleef
  timer: 60
  floor:
    blocktype: 35
    blockdata: 0
    rainbow: false
    corner1:
      x: 0.0
      y: 0.0
      z: 0.0
    corner2:
      x: 0.0
      y: 0.0
      z: 0.0
  pit:
    corner1:
      x: 0.0
      y: 0.0
      z: 0.0
    corner2:
      x: 0.0
      y: 0.0
      z: 0.0
  players:
    player1:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 180.0
      pitch: 0.0
    player2:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 180.0
      pitch: 0.0
    player3:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 180.0
      pitch: 0.0
    player4:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 180.0
      pitch: 0.0
  fireworks:
    firework1:
      x: 0.0
      y: 0.0
      z: 0.0
    firework2:
      x: 0.0
      y: 0.0
      z: 0.0
    firework3:
      x: 0.0
      y: 0.0
      z: 0.0
    firework4:
      x: 0.0
      y: 0.0
      z: 0.0
labels: {}